server {

	listen 80;

	root /usr/share/nginx/html;
	index index.html;

	location / {
		try_files $uri $uri/ /index.html;
	}

	location /api/ {
		proxy_pass http://backend:${BACKEND_INTERNAL_PORT};
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;

		if ($request_method = OPTIONS) {
			add_header Access-Control-Allow-Origin *;
			add_header Access-Control-Request-Methods "GET, POST, PUT, DELETE, PATCH, OPTIONS";
			add_header Access-Control-Allow-Headers "*";
			return 204;
		}
	}
}
