services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: appdb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: fastapi_backend
    restart: always
    depends_on:
      - db
    environment:
      - PROJECT_ENV=production
      - POSTGRES_URL=postgresql://appuser:strongpassword@db:5432/appdb
      - SECRET_KEY=supersecretkey123
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - BACKEND_INTERNAL_PORT=${BACKEND_INTERNAL_PORT:-8000}
    ports:
      - "${BACKEND:-8888}:${BACKEND_INTERNAL_PORT:-8000}"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: react_frontend
    restart: always
    environment:
      - BACKEND_INTERNAL_PORT=${BACKEND_INTERNAL_PORT:-8000}
    ports:
      - "${FRONTEND:-3000}:80"
    depends_on:
      - backend
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER:-8081}:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge